<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
<!--#if (IncludeAspire) -->
    <ProjectReference Include="..\CleanArchBlazorServer.ServiceDefaults\CleanArchBlazorServer.ServiceDefaults.csproj" />
<!--#endif -->
<!--#if (IncludeCleanArchitecture) -->
    <ProjectReference Include="..\CleanArchBlazorServer.Application\CleanArchBlazorServer.Application.csproj" />
    <ProjectReference Include="..\CleanArchBlazorServer.Infrastructure\CleanArchBlazorServer.Infrastructure.csproj" />
<!--#endif -->
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dorn.WebUI.Primitives" />
    <PackageReference Include="MudBlazor" />
  </ItemGroup>
</Project>
